name: Build Feature

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        continue-on-error: true

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Build project
        run: npm run build
        continue-on-error: true

        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./build # Adjust the path to your build output directory
        continue-on-error: true
